Fix lit subfolder tests failing when run via ninja check-triton-lit-tests-<folder> (#7966)
### Summary

This PR fixes an issue where running a specific lit test folder
(e.g., `Conversion`) using `ninja check-triton-lit-tests-<folder>` fails
with the error:
```
(triton) zzl@gtx1660:~/triton-project/triton/build/cmake.linux-x86_64-cpython-3.10$ ninja check-triton-lit-tests-conversion -v
[0/1] cd /home/zzl/triton-project/triton/build/cmake.linux-x86_64-cpython-3.10/test && /home/zzl/triton-project/triton/.venv/bin/python3 /home/zzl/triton-project/triton/.venv/bin/lit -sv /home/zzl/triton-project/triton/test/Conversion
lit: /home/zzl/triton-project/triton/.venv/lib/python3.10/site-packages/lit/TestingConfig.py:152: fatal: unable to parse config file '/home/zzl/triton-project/triton/test/lit.cfg.py', traceback: Traceback (most recent call last):
  File "/home/zzl/triton-project/triton/.venv/lib/python3.10/site-packages/lit/TestingConfig.py", line 140, in load_from_path
    exec(compile(data, path, "exec"), cfg_globals, None)
  File "/home/zzl/triton-project/triton/test/lit.cfg.py", line 17, in <module>
    config.test_format = lit.formats.ShTest(not llvm_config.use_lit_shell)
AttributeError: 'NoneType' object has no attribute 'use_lit_shell'

FAILED: test/CMakeFiles/check-triton-lit-tests-conversion /home/zzl/triton-project/triton/build/cmake.linux-x86_64-cpython-3.10/test/CMakeFiles/check-triton-lit-tests-conversion 
cd /home/zzl/triton-project/triton/build/cmake.linux-x86_64-cpython-3.10/test && /home/zzl/triton-project/triton/.venv/bin/python3 /home/zzl/triton-project/triton/.venv/bin/lit -sv /home/zzl/triton-project/triton/test/Conversion
ninja: build stopped: subcommand failed.
```

The issue is that llvm_config ends up being NoneType, because ninja
check is executed in ${CMAKE_CURRENT_SOURCE_DIR} instead of
${CMAKE_CURRENT_BINARY_DIR}.
As a result, lit.site.cfg.py is not invoked, which is supposed to call
lit.llvm.initialize and properly initialize llvm_config.

### Changes
	•	Run tests from the binary directory in TRITON-LIT-TESTS.
• Explicitly set MAIN_CONFIG to lit.site.cfg.py so that llvm_config is
initialized correctly.
### Related Issue
Fixes #7965

<!---
The core Triton is a small number of people, and we receive many PRs
(thank
you!).  To help us review your code more quickly, **if you are a new
contributor (less than 3 PRs merged) we ask that you complete the
following
tasks and include the filled-out checklist in your PR description.**

Complete the following tasks before sending your PR, and replace `[ ]`
with
`[x]` to indicate you have done them.
-->

# New contributor declaration
- [x] I am not making a trivial change, such as fixing a typo in a
comment.

- [x] I have written a PR description following these
  [rules](https://cbea.ms/git-commit/#why-not-how).

- [x] I have run `pre-commit run --from-ref origin/main --to-ref HEAD`.

- Select one of the following.
  - [ ] I have added tests.
    - `/test` for `lit` tests
    - `/unittest` for C++ tests
    - `/python/test` for end-to-end tests
  - [x] This PR does not need a test because `FILL THIS IN`.

- Select one of the following.
  - [x] I have not added any `lit` tests.
- [ ] The `lit` tests I have added follow these [best
practices](https://mlir.llvm.org/getting_started/TestingGuide/#filecheck-best-practices),
including the "tests should be minimal" section. (Usually running Python
code
    and using the instructions it generates is not minimal.)