[NFC] Limit the range of integers so that the sum does not overflow in reduce test case (#7470)
Our CI hit an overflow issue in reduce test case with Triton
Interpreter.

```
FAILED language/test_core.py::test_reduce1d[4-1-1-sum-int32-32] - triton.runtime.errors.InterpreterError: InterpreterError("OverflowError('Python integer -4736833654 out of bounds for int32')")
FAILED language/test_core.py::test_reduce1d[4-1-1-sum-int32-64] - triton.runtime.errors.InterpreterError: InterpreterError("OverflowError('Python integer -17340316748 out of bounds for int32')")
FAILED language/test_core.py::test_reduce1d[4-1-1-sum-int32-128] - triton.runtime.errors.InterpreterError: InterpreterError("OverflowError('Python integer -15950412024 out of bounds for int32')")
FAILED language/test_core.py::test_reduce1d[4-1-1-sum-int32-512] - triton.runtime.errors.InterpreterError: InterpreterError("OverflowError('Python integer 6080852592 out of bounds for int32')")
```

There is a comment in the test_reduce1d about limiting the range of
Integers in case overflow but without actual code.
Add the limitation as the comment.

---------

Signed-off-by: Lu,Chengjun <chengjun.lu@intel.com>
Co-authored-by: Thomas Raoux <thomas.raoux@openai.com>