[PROTON] Don't use designated initializers in `CuptiPCSampling.cpp` as it relates to c++20 (#5291)
Hi @Jokeren,

these changes relates to your PR:
https://github.com/triton-lang/triton/pull/4674, so I would like to ask
if this was done on purpose? (considering that the project declares
support for the c++17 standard).

I discovered this while trying to compile proton using MSVC. It looked
like this:
`\CuptiPCSampling.cpp(18): error C7555: use of designated initializers
requires at least '/std:c++20'`.

This might also be a good opportunity to ask you about your plans to
transition Triton to `с++20`.

---------

Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>