[DOC] Update LLVM build instructions. (#3782)
This commit updates the LLVM build instructions in the readme file. The
current instructions result in a triton build that fails at load-time
with the following error:

```
ImportError: /home/.../triton/python/triton/_C/libtriton.so: undefined symbol: LLVMInitializeSparcTarget
```

This flag is used in the triton docker files.