[RFC] Enable mypy typechecking on subset of files in pre-commit (#6704)
In https://github.com/triton-lang/triton/pull/6497 and
https://github.com/triton-lang/triton/pull/6467 I took care to ensure
the relevant modules typechecked successfully with mypy.

Now I want to make sure they stay this way, so I'm proposing including
`mypy` in the standard pre-commit flow. This way we can iteratively make
different files typecheck without fear of losing progress. Example UX
when creating type error:
```
> git diff --cached
diff --git a/python/triton/knobs.py b/python/triton/knobs.py
index dd291513d..eab3cca17 100644
--- a/python/triton/knobs.py
+++ b/python/triton/knobs.py
@@ -106,7 +106,7 @@ class env_int(env_base[int, int]):

     def from_env(self, val: str) -> int:
         try:
-            return int(val)
+            return str(int(val))
         except ValueError as exc:
             raise RuntimeError(f"Unable to use {self.key}={val}: expected int") from exc
> git commit -m tst
check for broken symlinks............................(no files to check)Skipped
detect destroyed symlinks................................................Passed
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...........................................(no files to check)Skipped
check toml...........................................(no files to check)Skipped
check python ast.........................................................Passed
check for added large files..............................................Passed
check for merge conflicts................................................Passed
check that executables have shebangs.................(no files to check)Skipped
check that scripts with shebangs are executable..........................Passed
detect private key.......................................................Passed
debug statements (python)................................................Passed
ruff.....................................................................Passed
yapf.....................................................................Passed
clang-format.........................................(no files to check)Skipped
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

python/triton/knobs.py:109: error: Incompatible return value type (got "str", expected "int")  [return-value]
Found 1 error in 1 file (checked 3 source files)

Expand YAML anchors..................................(no files to check)Skipped
```

And example UX when changing file that isn't typechecked (even though
the file has type errors):
```
> git diff --cached
diff --git a/python/triton/language/core.py b/python/triton/language/core.py
index 397b87560..9339cde9b 100644
--- a/python/triton/language/core.py
+++ b/python/triton/language/core.py
@@ -97,6 +97,7 @@ def _unwrap_iterable(x):
         # right answer for whether the class constexpr defines __iter__, and
         # abc.Iterable doesn't work (at least not without some metaclass magic).
         try:
+            _a: str = 5
             iter(x[0])
             return x[0]
         except TypeError:
> git commit -m tst
check for broken symlinks............................(no files to check)Skipped
detect destroyed symlinks................................................Passed
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...........................................(no files to check)Skipped
check toml...........................................(no files to check)Skipped
check python ast.........................................................Passed
check for added large files..............................................Passed
check for merge conflicts................................................Passed
check that executables have shebangs.................(no files to check)Skipped
check that scripts with shebangs are executable..........................Passed
detect private key.......................................................Passed
debug statements (python)................................................Passed
ruff.....................................................................Passed
yapf.....................................................................Passed
clang-format.........................................(no files to check)Skipped
mypy.....................................................................Passed
Expand YAML anchors..................................(no files to check)Skipped
[danzimm/mypycheck 9709ff131] tst
 1 file changed, 1 insertion(+)
```

N.B. In order to avoid duplicate inclusion/exclusion lists in
`pyproject.toml` and `.pre-commit-config.yaml` I've disabled passing
file names from pre-commit (since the CLI files override any lists in
`pyproject.toml`), since if we only specify the exlusions in
`pre-commit` running `mypy` directly wouldn't pick up that
configuration.